stages:
  - install
  - lint
  - deploy

install:
  stage: install
  image: node:14.15-alpine3.13
  script:
    - echo "Install dependencies"
    - npm install
  cache:
    paths:
      - node_modules
  only:
    refs:
      - main
      - develop
      - merge_request

lint:
  stage: lint
  image: node:14.15-alpine3.13
  script:
    - echo "Lint project"
    - npm run lint
  cache:
    paths:
      - node_modules
  only:
    refs:
      - main
      - develop
      - merge_request

deploy:
  image: kroniak/ssh-client
  stage: deploy
  environment:
    name: production
    url: https://culture.indahou.se
  script:
    - echo "Start deploy"
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$MASTER_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - rsync -avzr -e "ssh" --progress / $MASTER_HOST:/var/www/html
  only:
    - main
